CC=g++
CFLAGS=-c -Wall

all: lab3 #то, что будет по итогу компиляции
lab3: main4.o Dialog.o prog3.o 
main.o: g++ -c main4.cpp
Dialog.o: g++ -c Dialog.cpp
prog3.o: g++ -c prog3.cpp

clean: rm -rf *.o lab3
